import type { Candidate } from "../types/candidate";

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: 1,
    name: "Sarah Johnson",
    email: "sarah.johnson@email.com",
    phone: "+1-555-0101",
    position: "Senior Frontend Developer",
    status: "approved",
    skills: ["React", "TypeScript", "CSS", "Node.js"],
    experience: 5,
    rating: 4.5,
    appliedDate: "2024-10-15",
    interviewDate: "2024-10-20",
    notes: "Excellent technical skills and communication",
    yearlySalary: 95000,
    location: "San Francisco, CA",
    education: "BS Computer Science",
  },
  {
    id: 2,
    name: "Michael Chen",
    email: "michael.chen@email.com",
    phone: "+1-555-0102",
    position: "Full Stack Developer",
    status: "pending",
    skills: ["Java", "Spring Boot", "React", "PostgreSQL"],
    experience: 3,
    rating: 4.0,
    appliedDate: "2024-11-01",
    interviewDate: null,
    notes: "Strong backend experience, waiting for technical interview",
    yearlySalary: 80000,
    location: "New York, NY",
    education: "MS Software Engineering",
  },
  {
    id: 3,
    name: "Emily Rodriguez",
    email: "emily.rodriguez@email.com",
    phone: "+1-555-0103",
    position: "UI/UX Designer",
    status: "on-hold",
    skills: ["Figma", "Adobe XD", "CSS", "HTML"],
    experience: 4,
    rating: 4.2,
    appliedDate: "2024-10-25",
    interviewDate: "2024-10-28",
    notes: "Great portfolio, but needs approval from design lead",
    yearlySalary: 75000,
    location: "Austin, TX",
    education: "BA Graphic Design",
  },
  {
    id: 4,
    name: "David Kim",
    email: "david.kim@email.com",
    phone: "+1-555-0104",
    position: "DevOps Engineer",
    status: "approved",
    skills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    experience: 6,
    rating: 4.8,
    appliedDate: "2024-10-10",
    interviewDate: "2024-10-18",
    notes: "Exceptional DevOps skills, strong cultural fit",
    yearlySalary: 105000,
    location: "Seattle, WA",
    education: "BS Information Technology",
  },
  {
    id: 5,
    name: "Jessica Williams",
    email: "jessica.williams@email.com",
    phone: "+1-555-0105",
    position: "Junior Developer",
    status: "rejected",
    skills: ["JavaScript", "HTML", "CSS"],
    experience: 1,
    rating: 2.5,
    appliedDate: "2024-10-30",
    interviewDate: "2024-11-02",
    notes: "Lacks required experience for the role",
    yearlySalary: 55000,
    location: "Boston, MA",
    education: "BS Computer Science",
  },
  {
    id: 6,
    name: "Robert Taylor",
    email: "robert.taylor@email.com",
    phone: "+1-555-0106",
    position: "Backend Developer",
    status: "pending",
    skills: ["Python", "Django", "REST API", "MongoDB"],
    experience: 4,
    rating: 4.3,
    appliedDate: "2024-11-05",
    interviewDate: "2024-11-12",
    notes: "Interview scheduled, looks promising",
    yearlySalary: 88000,
    location: "Denver, CO",
    education: "MS Computer Science",
  },
  {
    id: 7,
    name: "Amanda Garcia",
    email: "amanda.garcia@email.com",
    phone: "+1-555-0107",
    position: "Project Manager",
    status: "approved",
    skills: ["Agile", "Scrum", "JIRA", "Communication"],
    experience: 7,
    rating: 4.6,
    appliedDate: "2024-10-20",
    interviewDate: "2024-10-25",
    notes: "Strong leadership and organizational skills",
    yearlySalary: 92000,
    location: "Chicago, IL",
    education: "MBA",
  },
  {
    id: 8,
    name: "Christopher Lee",
    email: "christopher.lee@email.com",
    phone: "+1-555-0108",
    position: "Mobile Developer",
    status: "pending",
    skills: ["React Native", "Swift", "Kotlin", "Firebase"],
    experience: 4,
    rating: 4.1,
    appliedDate: "2024-11-08",
    interviewDate: "2024-11-15",
    notes: "Strong mobile development background",
    yearlySalary: 90000,
    location: "Los Angeles, CA",
    education: "BS Computer Engineering",
  },
  {
    id: 9,
    name: "Michelle Thompson",
    email: "michelle.thompson@email.com",
    phone: "+1-555-0109",
    position: "Data Scientist",
    status: "approved",
    skills: ["Python", "Machine Learning", "TensorFlow", "SQL"],
    experience: 5,
    rating: 4.7,
    appliedDate: "2024-10-12",
    interviewDate: "2024-10-19",
    notes: "Excellent analytical skills and ML expertise",
    yearlySalary: 110000,
    location: "San Francisco, CA",
    education: "PhD Data Science",
  },
  {
    id: 10,
    name: "James Anderson",
    email: "james.anderson@email.com",
    phone: "+1-555-0110",
    position: "QA Engineer",
    status: "on-hold",
    skills: ["Selenium", "Jest", "Cypress", "API Testing"],
    experience: 3,
    rating: 3.8,
    appliedDate: "2024-11-03",
    interviewDate: "2024-11-10",
    notes: "Waiting for team capacity review",
    yearlySalary: 72000,
    location: "Portland, OR",
    education: "BS Software Engineering",
  },
  {
    id: 11,
    name: "Patricia Martinez",
    email: "patricia.martinez@email.com",
    phone: "+1-555-0111",
    position: "Security Engineer",
    status: "approved",
    skills: ["Cybersecurity", "Penetration Testing", "AWS", "Network Security"],
    experience: 6,
    rating: 4.9,
    appliedDate: "2024-10-08",
    interviewDate: "2024-10-16",
    notes: "Outstanding security expertise, highly recommended",
    yearlySalary: 115000,
    location: "Washington, DC",
    education: "MS Cybersecurity",
  },
  {
    id: 12,
    name: "Daniel Brown",
    email: "daniel.brown@email.com",
    phone: "+1-555-0112",
    position: "Frontend Developer",
    status: "rejected",
    skills: ["Vue.js", "HTML", "CSS", "JavaScript"],
    experience: 2,
    rating: 3.0,
    appliedDate: "2024-11-01",
    interviewDate: "2024-11-07",
    notes: "Skill set doesn't match our tech stack requirements",
    yearlySalary: 65000,
    location: "Miami, FL",
    education: "BA Web Development",
  },
  {
    id: 13,
    name: "Laura Wilson",
    email: "laura.wilson@email.com",
    phone: "+1-555-0113",
    position: "Cloud Architect",
    status: "pending",
    skills: ["Azure", "AWS", "GCP", "Terraform", "Microservices"],
    experience: 8,
    rating: 4.5,
    appliedDate: "2024-11-06",
    interviewDate: "2024-11-14",
    notes: "Senior-level candidate with impressive portfolio",
    yearlySalary: 130000,
    location: "Seattle, WA",
    education: "MS Cloud Computing",
  },
  {
    id: 14,
    name: "Kevin Harris",
    email: "kevin.harris@email.com",
    phone: "+1-555-0114",
    position: "Database Administrator",
    status: "on-hold",
    skills: ["MySQL", "PostgreSQL", "Oracle", "MongoDB", "Redis"],
    experience: 5,
    rating: 4.2,
    appliedDate: "2024-10-28",
    interviewDate: "2024-11-05",
    notes: "Budget approval pending",
    yearlySalary: 85000,
    location: "Atlanta, GA",
    education: "BS Information Systems",
  },
  {
    id: 15,
    name: "Sophia Davis",
    email: "sophia.davis@email.com",
    phone: "+1-555-0115",
    position: "Technical Writer",
    status: "approved",
    skills: [
      "Documentation",
      "Markdown",
      "API Docs",
      "Technical Communication",
    ],
    experience: 4,
    rating: 4.4,
    appliedDate: "2024-10-22",
    interviewDate: "2024-10-27",
    notes: "Excellent writing samples and communication skills",
    yearlySalary: 70000,
    location: "Boston, MA",
    education: "MA Technical Communication",
  },
];
